### ISSUE TITLE
Exception when stopping the consumer using `consumer.StopConsuming`

### ISSUE THREAD

**Issue by victorct-pronto** [wagslane/go-rabbitmq#21]
Hi, I got an exception whenever I stop the consumer by doing `consumer.StopConsuming`

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e4f38]

```
goroutine 54 [running]:
github.com/wagslane/go-rabbitmq.(*channelManager).startNotifyCancelOrClosed(0xc000242080)
	/go/pkg/mod/github.com/wagslane/go-rabbitmq@v0.6.0/channel.go:62 +0x158
created by github.com/wagslane/go-rabbitmq.newChannelManager
	/go/pkg/mod/github.com/wagslane/go-rabbitmq@v0.6.0/channel.go:34 +0x191
```

This is some basic code I'm doing:

```
func create_consumer() rabbitmq.Consumer {
	consumer, err := rabbitmq.NewConsumer("connection")
	if (err != nil){
		log.Fatal(err)
	}
	return consumer
}


func start_consuming(consumer *rabbitmq.Consumer) {
	err := consumer.StartConsuming(
		func(d rabbitmq.Delivery) bool {
			log.Printf("consumed: %v", string(d.Body))
			time.Sleep(5 * time.Second)
			log.Printf("consumed sleep: %v", string(d.Body))		
			// true to ACK, false to NACK
			return true
		},
		"testing_queue",
		[]string{"testing_queue"})
	if err != nil {
		log.Fatal(err)
	}

}

func main() {
	exit := make(chan os.Signal, 1)
	
	
	signal.Notify(exit, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	




	consumer := create_consumer()
	start_consuming(&consumer)
	<-exit

	consumer.StopConsuming()

}
```

**Comment by wagslane** [comment]
Should be fixed in 0.6.1. Let me know if you have more issues.
